#!/bin/sh
# altj - Explanation goes here
# Created: Tue Nov 25 11:06:22 MYT 2008
# args=$(wmctrl -l|grep -v -- '-1'|tr -s ' '|cut -f 4- -d' '|
# while read line; do
# echo "'$(echo $line|sed -e 's/ / /g')'"\ "'wmctrl -a \"$line\"'"
# done|tr '\n' '\n'|cat)
#echo $args
# ratmenu_opts="-style dreary -fg linen -bg black"
# eval ratmenu $ratmenu_opts "$args"

#echo -e "$args"|dmenu

exclude=term\.
currwin=`currwin`
windowlist=`goto|grep -v "term\."|sed -e 's/\s\+/ /g' -e 's/^ //'|cut -d' ' -f 1,5-`
if [ -z "$windowlist" ]; then
  exit
fi
nwindows=`echo "$windowlist"|wc -l`
echo nwindows=$nwindows
title=`echo "$windowlist"|dmenu -sb '#5c5cff' -l $nwindows`
if [ -n "$title" ]; then
	#wmctrl -a "$title"
	n=`echo $title|awk '{print $1}'`
	goto $n
else
  echo wmctrl -a $currwin
fi
