#!/bin/sh
# Created: Tue Dec 11 13:44:43 MYT 2012

lines=32
columns=110

eval "`xrandr|grep '\*'|awk '{print $1}'|sed -e 's/^/width=/' -e 's/x/ height=/'`; \
	`xftmetric dejavu\ sans\ mono 14`"
border_size=1
term_width=$((columns * XFTM_MAX_ADVANCE + 2 * border_size))
term_height=$((lines * (XFTM_ASCENT + XFTM_DESCENT) + 2 * border_size))
#echo $term_width
#echo $term_height
x=$(( width / 2 - term_width / 2 ))
y=$(( height / 2 - term_height / 2))
TERM_NAME=bigterm \
SHORT_TERM_NAME=b \
uxterm \
	-class BigTerm \
	-fg black -bg white \
	-title bigterm \
	-name term.b \
	-geometry ${columns}x${lines}+${x}+${y} \
	-e mux start ${1:-bigterm}
