#!/bin/sh
# browsertop - move browser windows such that their top is exactly $head_room
adjust_top_pos() {
  head_room=$1
  titles=$2
  for winid in $(wmctrl -l|awk "/$titles/"' { print $1 }')
  do
    #echo wmctrl -r $winid -e 0,-1,$head_room,-1,-1
    wmctrl -i -r $winid -e 0,-1,$head_room,-1,-1
  done
}

adjust_top_pos 3 'Chrome|Thunderbird'

# Skype didn't get the memo
adjust_top_pos 28 'Skype'
