#!/bin/sh
# cycle - cycle windows
# Created: Mon Jan 19 17:55:33 MYT 2009

# Usage: cycle <tmpfilename> <windowtitle>

me=`basename $0`
usage() {
cat <<EOF
NAME
  $me - Cycle windows

SYNOPSIS
  $me [-hv] <tmpfilename> <windowtitle>

DESCRIPTION

OPTIONS
  -h
    Show this help message

  -v
    Reverse match
EOF
}

v=
while getopts hv opt
do
  case "$opt" in
    h) usage ; exit;;
    v) v=-v;;
    \?) echo Unknown option ; exit;;
  esac
done
shift $(($OPTIND -1))

file_counter=/dev/shm/$1
title="$2"

if [ ! -f $file_counter ]; then
  echo 0 > $file_counter
fi
index=`cat $file_counter`
index=$(($index + 1))
n_instances=`wmctrl -l|egrep $v "$title"|wc -l`
if [ ! $index -lt $n_instances ]; then
	index=0
fi

# Emulate MRU
last=`stat --format=%Y $file_counter`
now=`date +%s`
diff=$((now - last))
if [ $diff -gt 1 ]; then
  index=$(($index - 1))
  if [ $index -eq -1 ]; then
	  index=$n_instances
  fi
fi
echo $index > $file_counter
choose=$(($index + 1))

choose=$(($index + 1))
window_id=`wmctrl -l|egrep $v "$title"|awk '{print $1}'|head -$choose|tail -1`
wmctrl -i -a $window_id
