#!/bin/sh
# Created: Mon Sep 10 16:02:57 MYT 2012

usage() {
    echo -n "DESCRIPTION
  dump - dump content of a screen session to stdout
USAGE
  dump [-h] <screen session>
"
#OPTIONS
}

while getopts h opt
do
  case "$opt" in
    h) usage ; exit;;
    \?) echo Unknown option ; exit;;
  esac
done
shift $(($OPTIND -1))

term=$1
if [ -z "$term" ]; then
  usage
fi

out=~/tmp/dump
screen -d -r $term -X hardcopy $out && cat $out
