#!/bin/sh
# Created: Mon Sep 10 16:02:57 MYT 2012
. `dirname $0`/common.sh

usage() {
    echo -n "DESCRIPTION
  dump - dump content of a muxer session to stdout
USAGE
  dump [-h] [-A] <muxer session>
OPTIONS
  -A
    Dump the scrollback buffer contents too

  -a
    Dump ascii characters only (non-ascii will be replaced with space)

  -c
    Use the previous 'cached' dump, do not ask muxer to redump.

  -d
    Show debugging messages

  -n
    Dry run.
"
#OPTIONS
}

pager=
from_cache=
dump_with_scrollback=
while getopts Aacdhn opt
do
  case "$opt" in
    A) dump_with_scrollback=-h;;
    a) pager="|tr -cd '[ -~\n]'";;
    d) debug=t;;
    c) from_cache=t;;
    h) usage ; exit;;
    n) dry_run=t;;
    \?) echo Unknown option ; exit;;
  esac
done
shift $(($OPTIND -1))

term=$1
if [ -z "$term" ]; then
  usage
fi

outputfile=~/tmp/dump.$term

if [ -n "$from_cache" ]; then
  cat $outputfile
  exit 0
fi

rm -f $outputfile
touch $outputfile
oldnlines=-1
exe "mux dump $dump_with_scrollback -s $term $outputfile"
if [ -n "$dump_with_scrollback" ]; then
  # It takes a while ...
  while [ `cat $outputfile|wc -l` -ne $oldnlines ]; do
    oldnlines=`cat $outputfile|wc -l`
    sleep .01
  done
fi
exe cat $outputfile $pager
