#!/bin/sh
# Created: Mon Sep 10 16:02:57 MYT 2012
. `dirname $0`/common.sh

usage() {
    echo -n "DESCRIPTION
  dump - dump content of a screen session to stdout
USAGE
  dump [-h] [-A] <screen session>
OPTIONS
  -A
    Dump the scrollback buffer contets too

  -c
    Use the previous 'cached' dump, do not ask screen to redump.

  -d
    Show debugging messages

  -n
    Dry run.
"
#OPTIONS
}

from_cache=
dump_with_scrollback=
while getopts Acdhn opt
do
  case "$opt" in
    A) dump_with_scrollback=-h;;
    d) debug=t;;
    c) from_cache=t;;
    h) usage ; exit;;
    n) dry_run=t;;
    \?) echo Unknown option ; exit;;
  esac
done
shift $(($OPTIND -1))

term=$1
if [ -z "$term" ]; then
  usage
fi

out=~/tmp/dump.$term

if [ -n "$from_cache" ]; then
  cat $out
  exit 0
fi

rm -f $out
touch $out
oldnlines=-1
exe "screen -d -r $term -X hardcopy $dump_with_scrollback $out"
if [ -n "$dump_with_scrollback" ]; then
  # It takes a while ...
  while [ `cat $out|wc -l` -ne $oldnlines ]; do
    oldnlines=`cat $out|wc -l`
    sleep .01
  done
fi
exe cat $out
