#!/bin/sh
tmpdir=/dev/shm
mux list|awk '{print $1" "$2}'|while read pid termname
do
  firstletter=`echo $termname|sed -e 's/\(.\).*/\1/'`
  winidfile=$tmpdir/term.$firstletter.winid
  xwininfo -root -tree|grep '"[t]erm\.'$firstletter'"'|awk '{print $1" "$2}' |
  while read hexwinid title
  do
    decwinid=`echo "ibase=16; $hexwinid"|sed -e 's/ 0x\(.*\)/\U\1/'|bc`
    echo "echo $decwinid > $winidfile"
    echo $decwinid > $winidfile
  done
done
