#!/usr/bin/env perl
use strict;
use warnings;
use FindBin;
use lib $FindBin::RealBin;
use WMGR home => $FindBin::RealBin;
use Screen;

my $muxer = WMGR::get_config('muxer');

if (scalar @ARGV == 0) {
    die "mux: Nothing to do";
}

my $cmd = shift @ARGV;
$muxer->runCmd($cmd, @ARGV);
