#!/usr/bin/env perl
use strict;
use warnings;
use FindBin;
use lib $FindBin::RealBin;
use WMGR home => $FindBin::RealBin;
use Screen;
use Tmux;

#my $muxer = WMGR::get_config('muxer');
my $muxer = 'Tmux';

if (scalar @ARGV == 0) {
    $muxer->cmd_help();
    exit 0;
}

if ($ARGV[0] eq '-h' || $ARGV[0] eq 'help') {
    print $muxer->cmd_help();
    exit 0;
}

my $cmd = shift @ARGV;
$muxer->runCmd($cmd, @ARGV);
