#!/bin/sh
alert() {
	zenity --error --text "$@"
}
die() {
	alert "$@"
	exit 1
}
currwin=$(currwin) || die "Could not get current window id"
#text="$(xclip -o)"
text="$(xclip -o|sed -e 's,\\,\\\\\\\\,g')"
if [ -z "$text" ]; then
	die "No text to paste?"
fi
if [ -n "$currwin" ]; then
	c=0
	echo "$text"|while read line
	do
		c=$((c + 1))
		if [ $c -gt 1 ]; then
			xdotool key KP_Enter
		fi
		xdotool type --window "$currwin" "$line"
	done
	# click don't work?
	#echo xdotool click --window "$currwin" 2
else
	die "Current window id is empty?"
fi
