#!/bin/sh

me=$(basename $0)

usage() {
    echo "Usage: $me <session name>
Check if shell in <session name> is ready"
}

while getopts "" opt
do
  case "$opt" in
    \?) echo Unknown option ; exit;;
  esac
done
shift $(($OPTIND -1))

if [ -z "$1" ]; then
  usage
  exit 0
fi
session_name=$1

PROMPT_REGEX='^\$ $'
dump "$session_name"|grep -v '^$'|tail -1|grep -q "$PROMPT_REGEX"
