#!/bin/sh
# Created: Fri Dec 28 12:16:12 MYT 2012

. `dirname $0`/common.sh

me=`basename $0`
usage() {
cat <<EOF
NAME
  $me - wait for given term for a ready shell prompt

SYNOPSIS
  $me [-hv] [-i N] <session name>

DESCRIPTION

OPTIONS
  -h
    Show this help message

  -i N
    Wait N seconds between checks. Default is 3. (N could be anything that
    sleep(1) understands)

  -n N
    When to give up waiting. N is the number of iterations

  -v
    Verbose output
EOF
}

debug=
n=0
dry_run=
interval=3
verbose=:
while getopts hi:n:v opt
do
  case "$opt" in
    h) usage ; exit;;
    i) interval="$OPTARG";;
    n) n="$OPTARG";;
    v) verbose=;;
    \?) echo Unknown option ; exit;;
  esac
done
shift $(($OPTIND -1))

if [ -z "$1" ]; then
	usage
	exit 1
fi

if ! mux listall|grep -q $1; then
	echo "Term session $1 does not exist"
	exit 1;
fi

c=0
$verbose echo -n "whendone $1 "
while ! termready $1; do
	$verbose echo -n .
	c=$((c + 1))
	if [ $n -gt 0 ]; then
	  if [ $c -eq $n ]; then
	    exit 1;
	  fi
	fi

	sleep $interval
done
$verbose echo
exit 0
